name: Flipsite Docs
description: Flipsite Docs
before:
  -
    logo:
      svg: flipsite.svg
      sr: Flipsite
      url: flipsite
    nav:
      flipsite|exact: Documentation
      flipsite/sections: Sections
      flipsite/components: Components
      github:
        url: https://github.com/flipsite/flipsite
        text: Github
    style:
      inherit: navbar0:wide
      section.border: border-b
pages:
  flipsite/sections:
    -
      breadcrumb:
        flipsite: Home
        flipsite/sections: Sections
      style: &breadcrumb
        section:
          border: null
          bgColor: bg-gray-25
          paddingX: px-5
          paddingY: py-3.75
          container:
            maxWidth: null
    -
      grid:
        colData: $sections.yaml
        colTpl:
          sectionPreview:
            url: flipsite/sections/{colData.key}
            section: '{colData.poster}'
          group:
            heading:xs: '{colData.name}'
            paragraph:xs: '{colData.count} sections'
      style: &setionGrid
        section:
          paddingX: px-5
          paddingY: pb-5
          bgColor: bg-gray-25
          border: border-b
          container:
            maxWidth: null
        grid:
          container:
            display: grid
            gridTemplateCols: grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5
            gap: gap-5
        grid.colsAll.group.container:
          display: flex
          justify: justify-between
          alignItems: items-center
          marginY: mt-2.5
  flipsite/sections/[category]:
    data: $sections.yaml
    sections:
      -
        breadcrumb:
          flipsite: Home
          flipsite/sections: Sections
          flipsite/category:
            url: flipsite/sections/[category]
            text: '{data.[category].name}'
        style: *breadcrumb
      -
        grid:
          colData: '{data.[category].data}'
          colTpl:
            sectionPreview:
              url: 'flipsite/sections/[category]/{colData.key}'
              section: '{colData.key}'
            # group:
            #   heading:xs: '{colData.key}'
            #   paragraph:xs: 'Variants: {colData.variants}'
        style: *setionGrid
  flipsite/sections/[category]/[section]:
    data: $sections.yaml
    sections:
      -
        breadcrumb:
          flipsite: Home
          flipsite/sections: Sections
          category:
            url: flipsite/sections/[category]
            text: '{data.[category].name}'
          section:
            url: flipsite/sections/[category]/[section]
            text: '[section]'
        style: *breadcrumb
      -
        sectionPreview:
          section: '[section]'
          json: true
        style:
          section:
            border: null
            bgColor: bg-gray-25
            paddingX: px-5
            paddingY: null
            container:
              maxWidth: null
          sectionPreview:
            container:
              border: null
              boxShadow: shadow
              bgColor: bg-white
      -
        script.ready.add: vendor/flipsite/flipsite/docs/docs-add-section.js
        svg: zondicons/add-solid
        paragraph:sm: 'Add section to:'
        group:
          button:link:sm:
            text: before
            url: '#before'
        style:
          section:
            bgColor: bg-gray-25
            paddingY: py-3.75
            paddingX: px-5
            border: border-b
            container:
              display: flex
              alignItems: items-center
              spaceX: space-x-2
              maxWidth: null
          svg:
            fill: fill-current
            textColor: text-green
          group:
            container:
              fontFamily: font-mono
              divide: divide-x
            button:
              marginX: px-2
              cursor: hover:cursor-pointer
      -
        nav:pills:onpage:
          content: Content
          style: Style
        style: navbar1
      -
        id: content
        sectionYaml.section: '[section]'
        style: &code
          section:
            paddingY: null
            paddingX: null
            container:
              empty: tr
          sectionYaml:
            container:
              bgColor: bg-dark-400
              display: block
              paddingY: py-3.75
              paddingX: px-5
              textSize: text-3
            attr.textColor: text-primary-300
            string.textColor: text-white
            number.textColor: text-blue-200
            literal.textColor: text-blue-200
            bullet.textColor: text-white


      -
        id: style
        sectionYaml.style: '[section]'
        style.section.display: hidden
        style: *code
