name: Flipsite Docs
description: Flipsite Docs
before:
  -
    logo:
      svg: flipsite.svg
      sr: Flipsite
      url: flipsite
    nav:
      flipsite: Documentation
      flipsite/sections: Sections
      flipsite/components: Components
      github:
        url: https://github.com/flipsite/flipsite
        text: Github
    style: navbar0:wide
pages:
  flipsite/sections:
    -
      breadcrumb:
        flipsite: Home
        flipsite/sections: Sections
      style: &breadcrumb
        section:
          paddingX: px-5
          paddingY: pt-2.5
          container:
            maxWidth: null
    -
      grid:
        colData: $sections.yaml
        colTpl:
          sectionPreview:
            url: flipsite/sections/{colData.key}
            section: '{colData.poster}'
          group:
            heading:xs: '{colData.name}'
            paragraph:xs: '{colData.count} sections'
      style: &setionGrid
        section:
          paddingX: px-5
          paddingY: pb-5 pt-2.5
          container:
            maxWidth: null
        grid:
          container:
            display: grid
            gridTemplateCols: grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5
            gap: gap-5
        grid.colsAll.group.container:
          display: flex
          justifyContent: justify-between
          alignItems: items-center
          marginY: mt-2.5
  flipsite/sections/[category]:
    data: $sections.yaml
    sections:
      -
        breadcrumb:
          flipsite: Home
          flipsite/sections: Sections
          flipsite/category:
            url: flipsite/sections/[category]
            text: '{data.[category].name}'
        style: *breadcrumb
      -
        grid:
          colData: '{data.[category].data}'
          colTpl:
            sectionPreview:
              url: 'flipsite/sections/[category]/{colData.key}'
              section: '{colData.key}'
            group:
              heading:xs: '{colData.key}'
              paragraph:xs: '{colData.variants} variants'

        style: *setionGrid
  flipsite/sections/[category]/[section]:
    data: $sections.yaml
    sections:
      -
        breadcrumb:
          flipsite: Home
          flipsite/sections: Sections
          category:
            url: flipsite/sections/[category]
            text: '{data.[category].name}'
          section:
            url: flipsite/sections/[category]/[section]
            text: '[section]'
        style: *breadcrumb
        style.section.bgColor: bg-gray-25
      -
        sectionPreview:
          section: '[section]'
          json: true
        style:
          section:
            bgColor: bg-gray-25
            paddingX: px-5
            paddingY: pt-2.5
            container:
              maxWidth: null
          sectionPreview:
            container:
              border: null
              boxShadow: shadow
              bgColor: bg-white
      -
        script.ready.add: vendor/flipsite/flipsite/docs/docs-add-section.js
        svg: zondicons/add-solid
        paragraph:sm: 'Add section to:'
        group:
          button:link:sm:
            text: before
            url: '#before'
        style:
          section:
            bgColor: bg-gray-25
            paddingY: py-2.5
            paddingX: px-5
            border: border-b mb-100
            container:
              display: flex
              alignItems: items-center
              spaceX: space-x-2
          svg:
            fill: fill-current
            textColor: text-green
          group:
            container:
              fontFamily: font-mono
              divide: divide-x
            button:
              marginX: px-2
              cursor: hover:cursor-pointer
  #     -
  #       grid:
  #         -
  #           group:
  #             paragraph: Add as page section in `site.yaml`
  #             # button:link:
  #             #   text: Copy
  #             #   url: '#'
  #             #   onclick: copyYaml(this)
  #           yamlPreview:
  #             root: '{data.[category].data.[section].site}'
  #             style: '{data.[category].item}[section]'
  #         -
  #           group:
  #             paragraph: Add to `style` in `theme.yaml`
  #             # button:link:
  #             #   text: Copy
  #             #   url: '#'
  #             #   onclick: copyYaml(this)
  #           yamlPreview:
  #             root: '{data.[category].data.[section].style}'
  #             options:
  #               wrap: '{data.[category].item}[section]'
  #       style:
  #         section:
  #           paddingX: px-5
  #           paddingY: pt-5
  #         grid:
  #           container:
  #             display: grid
  #             gap: gap-10
  #             gridTemplateCols: grid-cols-1
  #           colsAll:
  #             container.spaceY: space-y-2
  #             group:
  #               container:
  #                 display: flex justify-between align-center text-3.5
  #               paragraph:
  #                 textSize: text-3.5
  #                 fontWeight: font-light
  #                 markdown:
  #                   code:
  #                     bgColor: bg-primary-o20
  #                     textColor: text-primary-600
  #                     padding: px-1 py-0.5
  #                     marginX: mx-0.5
  #                     borderRadius: rounded
  #             yamlPreview:
  #               container:
  #                 display: block
  #                 bgColor: bg-black-o80
  #                 borderRadius: rounded
  #                 textSize: text-3.5
  #                 padding: p-3.5
  #                 overflow: overflow-hidden
  #               attr.textColor: text-primary-300
  #               string.textColor: text-white
  #               number.textColor: text-blue-200
  #               literal.textColor: text-blue-200
  #               bullet.textColor: text-white

  # flipsite/components:
  #   -
  #     breadcrumb:
  #       flipsite: Home
  #       flipsite/components: Components
  #     style: *breadcrumb
  # flipsite/components/heading:
  #   -
  #     breadcrumb:
  #       flipsite: Home
  #       flipsite/components: Components
  #       flipsite/components/heading: Heading
  #     style: *breadcrumb